server:
  port: 8080

spring:
  application:
    name: SPMS
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://140.143.140.103:3306/spms?useSSL=false&serverTimezone=UTC
    username: root
    password: chen0809
  data:
    redis:
      host: 140.143.140.103
      port: 6379
      password: chen0809
      database: 1

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true