server:
  port: 8090
  servlet:
    context-path: /api
spring:
  application:
    name: SPMS
  mail:
    protocol: smtp   # 协议
    host: smtp.yeah.net   # 服务器地址
    username: cikian@yeah.net   # 邮箱账号
    password: MFHLUDPMUPUYCFHX   # 邮箱密码
    default-encoding: UTF-8   # 默认编码
    properties:
      mail:
        #配置SSL 加密工厂
        smtp:
          ssl:
            #本地测试，先放开ssl
            enable: false
            required: false
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
    port: 25   # 端口号
  datasource:
    druid:
      url: jdbc:mysql://140.143.140.103:3306/spms?useSSL=false&serverTimezone=UTC
      username: root
      password: chen0809
      driver-class-name: com.mysql.cj.jdbc.Driver

      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      initial-size: 5
      max-active: 20

      min-idle: 3
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
  data:
    redis:
      host: 140.143.140.103
      port: 6379
      password: chen0809
      database: 1
  servlet:
    multipart:
      max-file-size: 5MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tCgbvmsKhp7hU8UiZPd
    accessKeySecret: uUPYGTjp5Wo96ziCMeCpiXlRBLVUkl
    bucketName: spms-hbwe
